#!/usr/bin/env python3
"""Create a non-secret, fail-closed project bot starter from the bundled asset."""

from __future__ import annotations

import argparse
import json
import re
import shutil
from datetime import datetime, timezone
from pathlib import Path


SKILL_ROOT = Path(__file__).resolve().parents[1]
TEMPLATE_ROOT = SKILL_ROOT / "assets" / "project-bot-starter"
TEXT_SUFFIXES = {
    "",
    ".example",
    ".json",
    ".md",
    ".py",
    ".service",
    ".template",
    ".toml",
    ".txt",
    ".yaml",
    ".yml",
}
CAPABILITY_LABELS = {
    "document_qa": "项目资料问答",
    "code_analysis": "代码检索与分析",
    "database_diagnostics": "数据库只读诊断",
    "log_analysis": "日志只读排查",
}


def slugify(value: str) -> str:
    slug = re.sub(r"[^a-z0-9]+", "-", value.lower()).strip("-")
    if not slug:
        raise ValueError("name must contain at least one ASCII letter or digit")
    if not re.fullmatch(r"[a-z][a-z0-9-]{1,62}", slug):
        raise ValueError("derived slug must start with a letter and contain 2-63 characters")
    return slug


def parse_databases(value: str) -> list[str]:
    allowed = {"none", "oracle", "postgresql", "mysql", "sqlserver"}
    items = [item.strip().lower() for item in value.split(",") if item.strip()]
    if not items:
        items = ["none"]
    invalid = sorted(set(items) - allowed)
    if invalid:
        raise ValueError(f"unsupported databases: {', '.join(invalid)}")
    if "none" in items and len(items) > 1:
        raise ValueError("database 'none' cannot be combined with another engine")
    return list(dict.fromkeys(items))


def parse_database_sources(values: list[str]) -> list[dict[str, object]]:
    sources: list[dict[str, object]] = []
    seen: set[str] = set()
    for raw in values:
        if ":" not in raw:
            raise ValueError("database environment must use ENVIRONMENT:ENGINE")
        environment, engine = (part.strip() for part in raw.split(":", 1))
        environment = environment.upper()
        engine = engine.lower()
        if not re.fullmatch(r"[A-Z][A-Z0-9_]{1,31}", environment):
            raise ValueError(f"invalid database environment label: {environment!r}")
        if engine not in {"oracle", "postgresql", "mysql", "sqlserver"}:
            raise ValueError(f"unsupported database engine: {engine}")
        if environment in seen:
            raise ValueError(f"duplicate database environment: {environment}")
        seen.add(environment)
        sources.append(
            {
                "environment": environment,
                "engine": engine,
                "dsn_env": f"DB_{environment}_DSN",
                "user_env": f"DB_{environment}_USER",
                "password_env": f"DB_{environment}_PASSWORD",
                "read_only_principal_required": True,
                "enabled": False,
            }
        )
    return sources


def prepare_output(path: Path) -> None:
    if path.exists():
        if not path.is_dir():
            raise ValueError(f"output exists and is not a directory: {path}")
        if any(path.iterdir()):
            raise ValueError(f"refusing to overwrite non-empty directory: {path}")
    else:
        path.mkdir(parents=True)


def render_tree(
    source: Path,
    target: Path,
    replacements: dict[str, str],
    *,
    service: str,
) -> None:
    for item in sorted(source.rglob("*")):
        relative = item.relative_to(source)
        if "__pycache__" in relative.parts or item.suffix.lower() == ".pyc":
            continue
        if relative.parts[:1] == ("service",) and item.is_file():
            if service == "none":
                continue
            if service == "launchd" and "launchd" not in item.name:
                continue
            if service == "systemd" and "systemd" not in item.name:
                continue
        rendered_parts = [replacements.get(part, part) for part in relative.parts]
        destination = target.joinpath(*rendered_parts)
        if item.is_dir():
            destination.mkdir(parents=True, exist_ok=True)
            continue
        destination.parent.mkdir(parents=True, exist_ok=True)
        if item.suffix.lower() in TEXT_SUFFIXES or item.name.startswith("."):
            text = item.read_text(encoding="utf-8")
            for key, value in replacements.items():
                text = text.replace(key, value)
            destination.write_text(text, encoding="utf-8")
        else:
            shutil.copy2(item, destination)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--intake",
        default="",
        help="Optional customer-intake.json generated by onboard_project_bot.py",
    )
    parser.add_argument("--name", default="", help="Human-facing project bot name")
    parser.add_argument(
        "--slug",
        default="",
        help="ASCII package slug; required when --name has no ASCII letters",
    )
    parser.add_argument("--output", required=True, help="New or empty output directory")
    parser.add_argument("--bot-name", default="", help="Feishu bot display name placeholder")
    parser.add_argument(
        "--secret-mode",
        choices=("env", "file"),
        default=None,
        help="Resolve secrets from environment variables or a restricted local TXT file",
    )
    parser.add_argument(
        "--service",
        choices=("launchd", "systemd", "none"),
        default=None,
    )
    parser.add_argument(
        "--databases",
        default="",
        help="Comma-separated: oracle,postgresql,mysql,sqlserver,none",
    )
    parser.add_argument(
        "--database-env",
        action="append",
        default=[],
        metavar="ENVIRONMENT:ENGINE",
        help="Repeat for concrete sources, for example UAT:oracle",
    )
    parser.add_argument(
        "--install-root",
        default="",
        help="Absolute deployment path used only in the preflight service template",
    )
    parser.add_argument(
        "--knowledge-source",
        default="",
        help="Optional onboarding knowledge directory containing raw/wiki/maps/evidence/sync",
    )
    args = parser.parse_args()

    if not TEMPLATE_ROOT.is_dir():
        raise SystemExit(f"template directory is missing: {TEMPLATE_ROOT}")

    try:
        intake: dict[str, object] = {}
        intake_root: Path | None = None
        if args.intake.strip():
            intake_path = Path(args.intake).expanduser().resolve()
            intake = json.loads(intake_path.read_text(encoding="utf-8"))
            if intake.get("schema_version") != 1:
                raise ValueError("unsupported intake schema_version")
            intake_root = intake_path.parent.parent
        intake_project = intake.get("project", {}) if isinstance(intake, dict) else {}
        intake_channel = intake.get("channel", {}) if isinstance(intake, dict) else {}
        intake_deployment = intake.get("deployment", {}) if isinstance(intake, dict) else {}
        intake_secret_provider = intake.get("secret_provider", {}) if isinstance(intake, dict) else {}
        channel_type = str(intake_channel.get("type") or "feishu").lower()
        if channel_type != "feishu":
            raise ValueError(
                "the current runtime starter supports channel.type=feishu only; "
                "add and test a channel adapter before generating another target"
            )
        name = (
            args.name.strip()
            or str(intake_project.get("display_name") or "").strip()
        )
        if not name:
            raise ValueError("--name is required unless --intake provides project.display_name")
        intake_slug = str(intake_project.get("slug") or "").strip()
        slug = slugify(args.slug or (f"{intake_slug}-bot" if intake_slug else name))
        package = slug.replace("-", "_")
        output = Path(args.output).expanduser().resolve()
        service = args.service or str(intake_deployment.get("service_manager") or "none")
        if service not in {"launchd", "systemd", "none"}:
            raise ValueError("the current starter supports service managers: none, launchd, systemd")
        secret_mode = args.secret_mode or str(intake_secret_provider.get("mode") or "env")
        if secret_mode not in {"env", "file"}:
            raise ValueError("secret mode must be env or file")
        database_env_values = list(args.database_env)
        if not database_env_values and isinstance(intake.get("databases"), list):
            database_env_values = [
                f"{item.get('environment', '')}:{item.get('engine', '')}"
                for item in intake["databases"]
                if isinstance(item, dict) and item.get("environment") and item.get("engine")
            ]
        databases = parse_databases(args.databases or "none")
        database_sources = parse_database_sources(database_env_values)
        if database_sources:
            source_engines = list(dict.fromkeys(str(item["engine"]) for item in database_sources))
            if databases == ["none"]:
                databases = source_engines
            elif not set(source_engines).issubset(databases):
                raise ValueError("--database-env uses an engine missing from --databases")
        install_root = (
            args.install_root.strip()
            or str(intake_deployment.get("working_directory") or "").strip()
            or "/ABSOLUTE/PROJECT/PATH"
        )
        if install_root != "/ABSOLUTE/PROJECT/PATH" and not Path(install_root).is_absolute():
            raise ValueError("--install-root must be an absolute path")
        knowledge_source: Path | None = None
        knowledge_source_raw = args.knowledge_source.strip()
        if not knowledge_source_raw and intake_root is not None and (intake_root / "knowledge").is_dir():
            knowledge_source_raw = str(intake_root / "knowledge")
        if knowledge_source_raw:
            knowledge_source = Path(knowledge_source_raw).expanduser().resolve()
            required_knowledge_dirs = {"raw", "wiki", "maps", "evidence", "sync"}
            if not knowledge_source.is_dir():
                raise ValueError("--knowledge-source must be a directory")
            missing_knowledge = sorted(
                name for name in required_knowledge_dirs if not (knowledge_source / name).is_dir()
            )
            if missing_knowledge:
                raise ValueError(
                    "--knowledge-source is missing: " + ", ".join(missing_knowledge)
                )
        prepare_output(output)
    except (OSError, ValueError) as exc:
        parser.error(str(exc))

    bot_name = args.bot_name.strip() or str(intake_channel.get("bot_name") or "").strip() or name
    replacements = {
        "__BOT_SLUG__": slug,
        "__PACKAGE_NAME__": package,
        "__BOT_TITLE__": name,
        "__FEISHU_BOT_NAME__": bot_name,
        "__SERVICE_KIND__": service,
        "__SECRET_MODE__": secret_mode,
        "__DATABASE_ENGINES_JSON__": json.dumps(databases, ensure_ascii=False),
        "__DATABASE_SOURCES_JSON__": json.dumps(database_sources, ensure_ascii=False),
        "__DATABASE_ENV_LINES__": (
            "\n".join(
                line
                for source in database_sources
                for line in (
                    f"{source['dsn_env']}=",
                    f"{source['user_env']}=",
                    f"{source['password_env']}=",
                )
            )
            or "# No database environments selected."
        ),
        "__DATABASE_SECRET_FILE_LINES__": (
            "\n".join(
                line
                for source in database_sources
                for line in (
                    f"{source['dsn_env']}=<set-locally>",
                    f"{source['user_env']}=<set-locally>",
                    f"{source['password_env']}=<set-locally>",
                )
            )
            or "# No database environments selected."
        ),
        "__INSTALL_ROOT__": install_root,
    }
    render_tree(TEMPLATE_ROOT, output, replacements, service=service)
    if knowledge_source is not None:
        shutil.copytree(knowledge_source, output / "knowledge", dirs_exist_ok=True)

    manifest = {
        "schema_version": 1,
        "generator": "project-agent-bootstrap",
        "generated_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "name": name,
        "slug": slug,
        "package": package,
        "service": service,
        "channel": channel_type,
        "secret_mode": secret_mode,
        "desired_capabilities": intake.get("desired_capabilities", []),
        "knowledge_imported": knowledge_source is not None,
        "intake_imported": bool(intake),
        "databases": databases,
        "database_sources": database_sources,
        "secrets_embedded": False,
        "scaffold_only": True,
        "deployment_ready": False,
    }
    (output / ".project-agent-bootstrap.json").write_text(
        json.dumps(manifest, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    selected_capabilities = [str(item) for item in intake.get("desired_capabilities", [])]
    (output / "CUSTOMER_HANDOFF.md").write_text(
        f"# {name}机器人交付状态\n\n"
        ">当前交付的是安全脚手架和项目知识库，不是已经上线的机器人。\n\n"
        "## 已完成\n\n"
        f"- 项目名称：{name}\n"
        f"- 消息渠道：{channel_type}\n"
        f"- 密钥方式：{secret_mode}（未复制密钥真值）\n"
        f"- 选定能力：{'、'.join(CAPABILITY_LABELS.get(item, item) for item in selected_capabilities) or '项目资料问答'}\n"
        f"- 知识库已带入：{'yes' if knowledge_source is not None else 'no'}\n\n"
        "## 上线前必须完成\n\n"
        "1. 接入并实测飞书消息收发适配器。\n"
        "2. 接入并实测 Codex Thread/Turn 运行时。\n"
        "3. 在白名单测试群验证事件去重、话题上下文和回复投递。\n"
        "4. 对所有数据库、代码和日志连接器做有界只读测试。\n"
        "5. 完成重启恢复、备份、监控和回滚验收。\n\n"
        "上述证据齐全前，`.project-agent-bootstrap.json` 必须保持 `scaffold_only=true`。\n",
        encoding="utf-8",
    )
    print(
        json.dumps(
            {
                "status": "created",
                "output": str(output),
                "package": package,
                "next": [
                    "Review config/bot.example.json and .env.example",
                    "Set secrets locally without committing them",
                    "Create an isolated virtual environment and run python -m pip install -e .",
                    "Run python -m unittest discover -s tests -v from that environment",
                    "Run the skill's validate_scaffold.py",
                    "Implement and live-test adapters before marking deployment ready",
                ],
            },
            ensure_ascii=False,
            indent=2,
        )
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
